### ISSUE TITLE
create DB for each point and route

### ISSUE THREAD

**Issue by kvlch** [ProjectGangster/SeniorProj#21]
P.S. PLEASE DO NOT MESS UP WITH "NaviActivity" AND "Route" CLASSES AT THIS TIME. I'm working on them.Thx

**Comment by pun2345** [comment]
Sry,
In NaviActivity I only inserted few lines of code to retrieve data from DB and it is not important you can delete them and I can add them back again.
In route, I will separate my code and make a new class. You can just call the function to get the data when I will have finished it.
